POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Test",
  "number": "123"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "",
  "number": "123"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Test no number",
  "number": ""
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Test",
  "number": "123"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
  "name": "Dan Abramov", 
  "number": "12-43-234345"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
  "name": "Test Exists", 
  "number": "12345"
}
