GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/6abb9d6a98978215b2517f5b

###
GET http://localhost:3001/api/unknownEndpoint

###
GET http://localhost:3001/api/persons/unknownEndpoint
