POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "root",
  "name": "Superuser",
  "password": "Sekret"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "hellas",
  "name": "Arto Hellas",
  "password": "Arto Hellas"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "mluukkai",
  "name": "Matti Luukkainen",
  "password": "Matti Luukkainen"
}
