POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "test",
  "author": "author",
  "url": "http://localhost:3001/",
  "likes": 0
}

### test no title
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "",
  "author": "author",
  "url": "http://localhost:3001/",
  "likes": 0
}

### with user
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "test",
  "author": "author",
  "url": "http://localhost:3001/",
  "likes": 0,
  "userId": "6ac629e9837e2b95eefbfd9c"
}
